server:
  shutdown: graceful

spring:
  devtools:
    add-properties: true
  application:
    name: Stock&Cook
  datasource:
    url: jdbc:postgresql://localhost:5432/stockncook
    driver-class-name: org.postgresql.Driver
    username: xxx
    password: xxx
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
